## Create a self-signed Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: mongodb
spec:
  selfSigned: {}
## Create our in-house CA certificate and key using our self-signed Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: in-house-ca
  namespace: mongodb
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: in-house-ca
  secretName: in-house-ca

  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
## Create an issuer from our in-house CA secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: in-house-ca
  namespace: mongodb
spec:
  ca:
    secretName: in-house-ca
## Create Intermediate CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: in-house-intermediate
 namespace: mongodb
spec:
  isCA: true
  secretName: in-house-intermediate
  commonName: in-house-intermediate
  issuerRef:
    name: in-house-ca
  usages:
    - digital signature
    - key encipherment
    - cert sign
## Create an issuer from our in-house CA secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: in-house-intermediate
  namespace: mongodb
spec:
  ca:
    secretName: in-house-intermediate
## Create a MongoDB Agent Certificate from our in-house CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mdb-test-tls-agent-certs
  namespace: mongodb
spec:
  ## secretName is alwayse required
  secretName: mdb-test-tls-agent-certs
  commonName: mongodb-agent
  subject:
    organizationalUnits:
      - MongoDB Agents
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  # commonName: mongodb.svc.cluster.local
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  usages:
    - client auth
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: in-house-intermediate
    kind: Issuer
    group: cert-manager.io
## Create a MongoDB Server Certificate from our in-house CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mdb-test-tls-cert
  namespace: mongodb
spec:
  ## secretName is alwayse required
  secretName: mdb-test-tls-cert
  subject:
    organizationalUnits:
     - TSE
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  # commonName: mongodb.svc.cluster.local
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  usages:
    - server auth
    - client auth
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048

  dnsNames:
    - test-tls-0.test-tls-svc.mongodb.svc.cluster.local
    - test-tls-1.test-tls-svc.mongodb.svc.cluster.local
    - test-tls-2.test-tls-svc.mongodb.svc.cluster.local
    - test-tls-0
    - test-tls-1
    - test-tls-2
    - node01
    - node01.jalder.net
    - localhost

  issuerRef:
    name: in-house-intermediate
    kind: Issuer
    group: cert-manager.io
